### ISSUE TITLE
Feature Request: a method for manipulating point clouds

### ISSUE THREAD

**Issue by eric-schleicher** [andrewnakas/OpenBrushVR#1]
It would be awesome to be able to visualize tango point cloud captures in a proper VR environment.   I can envision a number of clever tools that would help align paneled captures as well as tweak noisy/messy sections of clouds.  

I continually find myself frustrated with selection paradigms on 2d displays and i think that tools for direct manipulation in a 3d would be truly useful part of a cloud capture and meshing workflow.

Think something like this might be in scope for open brush (vive experience)?

I wouldn't mind working on this and contributing if we think it would fit.

**Comment by eric-schleicher** [comment]
found this (stale) : https://github.com/smokelore/UnityPointCloud

**Comment by andrewnakas** [comment]
Yah definitely thought about doing that for tango! my friend Tim Swan has
been building a holodeck that can sync Tango with the Vive and Kinect.
https://www.youtube.com/watch?v=iZ86VlmgzgY

I'm definitely planning on using the tango mesh builder to edit vertex
information of meshes in app. I'm not entirely sure if point clouds are in
the full scope of open brush but definitely open to the idea.

Cheers,
-Nakas
